'use client'

import { useState } from 'react'
import Image from 'next/image'
import { OutputRecord } from '../../hooks/useAIStudio'
import { MODEL_REGISTRY } from '../../lib/models/modelConfig'
import { Copy, Check, Trash2, Bookmark, BookmarkCheck, Play, Volume2, Film } from 'lucide-react'

interface OutputCardProps {
  record: OutputRecord
  isActive: boolean
  onSelect: () => void
  onToggleSave: () => void
  onDelete: () => void
}

export function OutputCard({ record, isActive, onSelect, onToggleSave, onDelete }: OutputCardProps) {
  const [copied, setCopied] = useState(false)
  const [isPlayingAudio, setIsPlayingAudio] = useState(false)

  const model = MODEL_REGISTRY.find(m => m.id === record.modelId)
  
  // Clean formatting for Task names
  const getTaskLabel = () => {
    return record.task.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ')
  }

  const handleCopy = async (e: React.MouseEvent) => {
    e.stopPropagation()
    try {
      await navigator.clipboard.writeText(record.outputText)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch (err) {
      console.error('Failed to copy to clipboard:', err)
    }
  }

  return (
    <div
      onClick={onSelect}
      className={`relative w-full text-left p-4 rounded-xl border transition-all duration-300 cursor-pointer ${
        isActive
          ? 'bg-white/[0.03] border-teal-500/60 shadow-[0_4px_25px_rgba(20,184,166,0.05)]'
          : 'bg-[#0E0E10]/40 border-white/[0.02] hover:bg-white/[0.01] hover:border-white/[0.06]'
      }`}
      id={`output-card-${record.id}`}
    >
      {/* Visual Header */}
      <div className="flex justify-between items-start gap-2 border-b border-white/[0.03] pb-3 mb-3">
        <div className="truncate">
          <span className="font-sans font-medium text-[10px] tracking-wider uppercase text-teal-400 block">
            {getTaskLabel()}
          </span>
          <span className="font-mono text-[9px] text-slate-500 block leading-none mt-1">
            Generated by {model?.name || record.modelId} • {record.createdAt}
          </span>
        </div>

        {/* Top Actions */}
        <div className="flex gap-1.5 z-10 shrink-0" onClick={(e) => e.stopPropagation()}>
          <button
            onClick={onToggleSave}
            className={`p-1.5 rounded transition-all duration-200 active:scale-90 ${
              record.isSaved
                ? 'bg-amber-400/10 text-amber-400 border border-amber-400/20'
                : 'bg-white/[0.02] hover:bg-white/[0.08] text-slate-500 hover:text-slate-300 border border-white/[0.03]'
            }`}
            title={record.isSaved ? 'Remove from bookmarked items' : 'Bookmark this item'}
          >
            {record.isSaved ? <BookmarkCheck className="w-3.5 h-3.5" /> : <Bookmark className="w-3.5 h-3.5" />}
          </button>

          <button
            onClick={handleCopy}
            className="p-1.5 rounded bg-white/[0.02] hover:bg-white/[0.08] text-slate-500 hover:text-slate-200 border border-white/[0.03] transition-all duration-200 active:scale-90"
            title="Copy selection content text"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400 animate-bounce" /> : <Copy className="w-3.5 h-3.5" />}
          </button>

          <button
            onClick={onDelete}
            className="p-1.5 rounded bg-white/[0.02] hover:bg-rose-500/10 text-slate-500 hover:text-rose-400 border border-white/[0.03] hover:border-rose-500/15 transition-all duration-200 active:scale-90"
            title="Delete this historical generation"
          >
            <Trash2 className="w-3.5 h-3.5" />
          </button>
        </div>
      </div>

      {/* Output Content Preview */}
      <div className="space-y-3">
        {/* Render Text Snippet */}
        <div className="font-sans text-xs text-slate-300 leading-normal max-h-24 overflow-hidden text-ellipsis line-clamp-3">
          {record.outputText.replace(/^[#*-`\s]+/, '').substring(0, 180)}
          {record.outputText.length > 180 ? '...' : ''}
        </div>

        {/* ── IMAGE GENERATION VISUALIZER ── */}
        {record.imageUrl && (
          <div className="relative w-full aspect-video rounded-lg overflow-hidden border border-white/10 group mt-2 bg-slate-900 shadow-inner">
            <Image
              src={record.imageUrl}
              alt={record.prompt}
              fill
              referrerPolicy="no-referrer"
              className="object-cover group-hover:scale-105 transition-transform duration-700 pointer-events-none"
            />
            <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-transparent to-transparent flex items-end p-2 p-3">
              <span className="font-sans text-[9px] text-white font-medium bg-black/45 px-1.5 py-0.5 rounded backdrop-blur-sm truncate max-w-[90%] block">
                {record.prompt.substring(0, 60)}...
              </span>
            </div>
          </div>
        )}

        {/* ── AUDIO TTS PLAYER VISUALIZER ── */}
        {record.audioUrl && (
          <div className="mt-2.5 p-3 rounded-lg bg-cyan-950/20 border border-cyan-500/10 flex items-center justify-between gap-3 select-none">
            <div className="flex items-center gap-2">
              <div className="w-7 h-7 bg-cyan-500/10 text-cyan-400 rounded-full flex items-center justify-center border border-cyan-500/20">
                <Volume2 className="w-3.5 h-3.5" />
              </div>
              <div>
                <span className="font-sans text-[10px] font-medium text-slate-200 block">Synthesized Audio Output</span>
                <span className="font-mono text-[9px] text-slate-500 block">eleven_multilingual_v2 • 24.3kb</span>
              </div>
            </div>
            
            <audio
              controls
              src={record.audioUrl}
              className="h-6 max-w-[120px] md:max-w-none scale-90 origin-right opacity-80"
            />
          </div>
        )}

        {/* ── VIDEO RENDER VISUALIZER ── */}
        {record.videoUrl && (
          <div className="mt-2.5 rounded-lg border border-rose-500/10 overflow-hidden relative group aspect-video shadow-inner bg-slate-950 flex items-center justify-center">
            <video
              src={record.videoUrl}
              controls
              muted
              autoPlay
              loop
              playsInline
              className="absolute inset-0 w-full h-full object-cover pointer-events-auto"
            />
            {/* Tiny tag overlay indicating dynamic clip status */}
            <div className="absolute top-2 left-2 z-10 bg-black/60 px-1.5 py-0.5 rounded text-[8px] font-sans text-rose-400 flex items-center gap-1 backdrop-blur-sm">
              <Film className="w-2.5 h-2.5" /> HTML5 Visual
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
